### ISSUE TITLE
如何解决vgo无法下载某些依赖包的情况？

### ISSUE THREAD

**Issue by lianghuazhu0501** [wuyumin/vgo#1]
go: finding golang.org/x/sys v0.0.0-20180622082034-63fc586f45fe
go: finding golang.org/x/net v0.0.0-20180621144259-afe8f62b1d6b
go: golang.org/x/sys@v0.0.0-20180622082034-63fc586f45fe: git fetch -f https://go.googlesource.com/sys refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/lianghuazhu/go/src/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846: exit status 128:
	fatal: unable to access 'https://go.googlesource.com/sys/': Failed to connect to go.googlesource.com port 443: Operation timed out
go: golang.org/x/net@v0.0.0-20180621144259-afe8f62b1d6b: git fetch -f https://go.googlesource.com/net refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/lianghuazhu/go/src/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Operation timed out
go: error loading module requirements

这是我的报错信息，墙也翻但是就是下载不成成

**Comment by wuyumin** [comment]
vgo已经升级为Go的模块功能，参考一下
https://github.com/wuyumin/tutorial/blob/master/zh-cn/Modules/README.md
设置一下模块代理就可以下载了@lianghuazhu0501

**Comment by lianghuazhu0501** [comment]
解决了...非常感谢你的文章分享....
